apiVersion: v1
kind: DeploymentConfig
metadata:
  name: omar-mensa-app
  namespace: omar-dev
  selfLink: /oapi/v1/namespaces/omar-dev/deploymentconfigs/omar-mensa-app
  uid: dcdddf2c-82c2-11e7-ba3b-0e704fd9c8b2
  resourceVersion: '9375067'
  generation: 530
  creationTimestamp: '2017-08-16T20:38:29Z'
  labels:
    app: omar-openshift
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - omar-mensa-app
        from:
          kind: ImageStreamTag
          namespace: o2
          name: 'omar-mensa-app:latest'
        lastTriggeredImage: >-
          172.30.181.173:5000/o2/omar-mensa-app@sha256:8f99c4307cedee2f43f4568a6b24fe62239ec3f3ab25b681f93a88bf659b30b8
  replicas: 1
  test: false
  selector:
    app: omar-openshift
    deploymentconfig: omar-mensa-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: omar-openshift
        deploymentconfig: omar-mensa-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      volumes:
        - name: volume-mensa
          persistentVolumeClaim:
            claimName: ossim-data-dev-pvc
      containers:
        - name: omar-mensa-app
          image: >-
            172.30.181.173:5000/o2/omar-mensa-app@sha256:8f99c4307cedee2f43f4568a6b24fe62239ec3f3ab25b681f93a88bf659b30b8
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
            - name: SPRING_CLOUD_CONFIG_LABEL
              value: master
            - name: OSSIM_PREFS_FILE
              value: /usr/share/ossim/ossim-site-preferences
            - name: OSSIM_INSTALL_PREFIX
              value: /usr
            - name: OSSIM_DATA
              value: /data
            - name: BUCKETS
              value: o2-test-data
          resources: {}
          volumeMounts:
            - name: volume-mensa
              mountPath: /data
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add:
                - SYS_ADMIN
            privileged: true
            runAsUser: 1001
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
status:
  latestVersion: 524
  observedGeneration: 530
  replicas: 1
  updatedReplicas: 1
  availableReplicas: 1
  unavailableReplicas: 0
  details:
    message: image change
    causes:
      - type: ImageChange
        imageTrigger:
          from:
            kind: ImageStreamTag
            namespace: o2
            name: 'omar-mensa-app:latest'
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2017-11-27T21:08:18Z'
      lastTransitionTime: '2017-11-27T21:08:18Z'
      message: Deployment config has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2017-12-06T17:02:24Z'
      lastTransitionTime: '2017-12-06T17:02:22Z'
      reason: NewReplicationControllerAvailable
      message: replication controller "omar-mensa-app-524" successfully rolled out
  readyReplicas: 1
